name: Build Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install Packages
        run: |
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
          brew install openssl
      - name: Build Toolchain
        run: |
          source ./tools/rc/setup.sh
          rc --make-host-toolchain
      - name: Build PureDarwin
        run: |
          source ./tools/rc/setup.sh
          rc build
